name: example_model
type: actor # actor or critic
activation: relu
conv:
  activation: relu
  hidden_layers:
    - type: conv2d
      filters: 32
      kernel_size: 3
      padding: same
      activation: relu
      repeat: 3
  output_layer:
    units: 256
    activation: relu
dense:
  activation: relu
  hidden_layers:
    - type: dense
      units: 128
      activation: relu
      repeat: 1
optimizer: 
  type: adam
  learning_rate: 0.001

# example_config = {
#     "name": "example_model", 
#     "conv": {
#         "hidden_layers": [
#             {"type":"conv2d", "filters":32, "kernel_size":3, "padding":"same", "activation":"relu"}, 
#             {"type":"conv2d", "filters":32, "kernel_size":3, "padding":"same", "activation":"relu"}, 
#             {"type":"conv2d", "filters":32, "kernel_size":3, "padding":"same", "activation":"relu"}
#         ], 
#         "output_layer": {"units": 256, "activation": "relu"}
#     }, 
#     "dense": {
#         "hidden_layers": [
#             {"type": "dense", "units": 128, "activation": "relu"}
#         ],
#         "output_layer": {"units": 1, "activation": "softmax"}
#     }, 
#     "optimizer": {"type": "adam", "learning_rate": 0.001}, 
#     "loss": "binary_crossentropy", 
#     "metric": "binary_crossentropy"
# }